version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exercise_db

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'


# commadns for run
#  sudo docker-compose up -d --build
#  sudo docker-compose down